name: Recovery CI

on:
  workflow_dispatch:

jobs:
  twrp:
    name: TWRP Builder
    runs-on: ubuntu-18.04

    steps:
      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
      - name: Syncing TWRP sources
        run: |
          mkdir ~/TWRP
          cd ~/TWRP
          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
          git clone https://github.com/TeamWin/android_device_samsung_jflte -b android-7.1 ~/TWRP/device/samsung/jflte
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
      - name: Building TWRP
        run: |
          cd ~/TWRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          lunch omni_jflte-eng
          mka recoveryimage
      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v2
        with:
          name: TWRP_jflte
          path: /home/runner/TWRP/out/target/product/jflte/recovery.img
