name: LineageOS Recovery CI

on:
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    env:
      OEM: samsung
      DEVICE: j1pop3g

    steps:
    - uses: actions/checkout@v2

    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bc axel bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        mkdir ~/.jdk_7
        cd ~/.jdk_7
        axel -q -n $(nproc --all) https://repo.huaweicloud.com/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin
        chmod +x jdk-6u45-linux-x64.bin
        ./jdk-6u45-linux-x64.bin
        sudo update-alternatives --install /usr/bin/javac javac  $PWD/jdk1.6.0_45/bin/javac 2
        sudo update-alternatives --set javac $PWD/jdk1.6.0_45/bin/javac
        sudo update-alternatives --install /usr/bin/java java  $PWD/jdk1.6.0_45/bin/java 2
        sudo update-alternatives --set java $PWD/jdk1.6.0_45/bin/java
        sudo update-alternatives --install /usr/bin/javaws javaws  $PWD/jdk1.6.0_45/bin/javaws 2
        sudo update-alternatives --set javaws $PWD/jdk1.6.0_45/bin/javaws
        sudo update-alternatives --install /usr/bin/javadoc javadoc  $PWD/jdk1.6.0_45/bin/javadoc 2
        sudo update-alternatives --set javadoc $PWD/jdk1.6.0_45/bin/javadoc
        sudo update-alternatives --install /usr/bin/javah javah  $PWD/jdk1.6.0_45/bin/javah 2
        sudo update-alternatives --set javah $PWD/jdk1.6.0_45/bin/javah
        sudo update-alternatives --install /usr/bin/javap javap  $PWD/jdk1.6.0_45/bin/javap 2
        sudo update-alternatives --set javap $PWD/jdk1.6.0_45/bin/javap
        sudo update-alternatives --install /usr/bin/jar jar  $PWD/jdk1.6.0_45/bin/jar 2
        sudo update-alternatives --set jar $PWD/jdk1.6.0_45/bin/jar
        sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
    - name: Syncing LineageOS sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/LineageOS-ARMv6/android -b cm-11.0
        git clone https://github.com/LineageOS-ARMv6/android_device_samsung_bcm21553-common -b cm-11.0 ~/TWRP/device/samsung/bcm21553-common
        git clone https://github.com/LineageOS-ARMv6/android_hardware_broadcom_brcm_usrlib -b cm-11.0 ~/TWRP/hardware/broadcom/brcm_usrlib
        git clone https://github.com/LineageOS-ARMv6/android_hardware_broadcom_fmradio -b cm-11.0 ~/TWRP/hardware/broadcom/fmradio
        git clone https://github.com/LineageOS-ARMv6/android_kernel_samsung_bcm21553-common -b cm-11.0 ~/TWRP/kernel/samsung/bcm21553-common
        git clone https://github.com/LineageOS-ARMv6/android_device_samsung_totoro -b cm-11.0 ~/TWRP/device/samsung/totoro
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Building Lineage Recovery
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/TWRP
        rm -rf ~/TWRP/build
        git clone https://github.com/unlegacy-devices/android_build-ARMv6 -b cm-11.0 ~/TWRP/build
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch lineage_totoro-eng
        make -j$(nproc --all) bootimage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: Uploading LineageRecovery builds
      uses: actions/upload-artifact@v2
      with:
        name: twrp
        path: /home/runner/TWRP/out/target/product/kylepro/boot.img
